### ISSUE TITLE
Unable to install using pip or Cloning 

### ISSUE THREAD

**Issue by bikramkhastgir** [Savvysherpa/slda#10]
I am still getting the same error, when trying to install it without using conda.
Is there any solution to fixing it?
Environment: Python: 2.7
Method of installing: pip install slda (also tried by cloning directory)
******************************************************************************
Error:
Complete output from command python setup.py egg_info:
/bin/sh: 1: gsl-config: not found
Traceback (most recent call last):
    File "", line 1, in 
    File "/tmp/pip-install-vad3l5eo/slda/setup.py", line 10, in 
        library_dirs=[cython_gsl.get_library_dir()],
    File "/home/user/Env/KG/lib/python3.5/site-packages/cython_gsl/init.py", line 45, in get_library_dir
        lib_gsl_dir = os.popen('gsl-config --libs').read().split()[0][2:]
IndexError: list index out of range

**Comment by jvahl** [comment]
same here. Was anyone able to make the package run again?
