### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by xiaoleihuang** [Savvysherpa/slda#2]
I used python3 with sudo pip install .
But with following error:   

 Complete output from command python setup.py egg_info:
    /bin/sh: 1: gsl-config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-tmx65jji-build/setup.py", line 19, in <module>
        library_dirs=[cython_gsl.get_library_dir()],
      File "/usr/local/lib/python3.5/dist-packages/cython_gsl/__init__.py", line 45, in get_library_dir
        lib_gsl_dir = os.popen('gsl-config --libs').read().split()[0][2:]
    IndexError: list index out of range

**Comment by burbma** [comment]
Have you tried installing it using conda-forge? See [here](https://github.com/conda-forge/slda-feedstock).

**Comment by cvipul** [comment]
Conda forge has a dependency error :

UnsatisfiableError: The following specifications were found to be in conflict:
  - pypolyagamma -> python 3.5*
  - python 2.7*

**Comment by burbma** [comment]
Sorry for the delay. I believe it is fixed. Re-open if you still have problems.

**Comment by bikramkhastgir** [comment]
I am still getting the same error, when trying to install it without using conda.
Is there any solution to fixing it?
Environment: Python: 2.7 
Method of installing: pip install slda
***********************************
Error:
Complete output from command python setup.py egg_info:
    /bin/sh: 1: gsl-config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vad3l5eo/slda/setup.py", line 10, in <module>
        library_dirs=[cython_gsl.get_library_dir()],
      File "/home/user/Env/KG/lib/python3.5/site-packages/cython_gsl/__init__.py", line 45, in get_library_dir
        lib_gsl_dir = os.popen('gsl-config --libs').read().split()[0][2:]
    IndexError: list index out of range
